import logging
from typing import Any

from app.services.llm_service import LLMService

logger = logging.getLogger(__name__)


class SectionGenerationService:
    def __init__(self, llm_service: LLMService | None = None) -> None:
        self._llm_service = llm_service or LLMService()

    async def generate_section(
        self,
        topic: str,
        section_title: str,
        section_description: str,
        keyword: str,
        context: str,
    ) -> dict[str, Any]:
        """
        Generates 300-600 words of high-quality content for a specific section.
        Uses Tavily context as source of truth, avoiding direct copying.
        Produces original, SEO-optimized text returning 'body' and 'tokens_used'.
        """
        system_prompt = (
            "You are a senior SEO copywriter. "
            "Write highly engaging, factual, and informative article sections. "
            "Do NOT copy the given context directly; synthesize it into an improved original prose. "
            "Return strict JSON with key 'body' that contains the section text in markdown. "
            "Include useful details, not generic filler. Write in a clear and engaging way. "
            "Do not include the section title as a heading in the text, just return the paragraphs."
        )

        user_prompt = f"Topic: {topic}\n"
        user_prompt += f"Section Title: {section_title}\n"
        if section_description:
            user_prompt += f"Section Details/Focus: {section_description}\n"
        user_prompt += f"Target Keyword: {keyword}\n\n"

        if context:
            user_prompt += f"Web Context (Use as source of truth, but rewrite originally):\n{context}\n\n"

        user_prompt += (
            "Write 300-600 words of high-quality content. "
            "Ensure the target keyword is included naturally. "
            "Return JSON with 'body' key."
        )

        result = await self._llm_service.generate_json(
            system_prompt=system_prompt,
            user_prompt=user_prompt,
            temperature=0.5,
            max_tokens=1500,
        )

        data = result.data if isinstance(result.data, dict) else {}
        body = data.get("body", "")

        if not body:
            logger.warning("Empty body generated by LLM for section.")
            # Fallback if empty to avoid pipeline breaking completely
            heading = section_title or "Section"
            body = f"This section covers {heading}. We will expand on this topic shortly."

        return {
            "body": str(body).strip(),
            "tokens_used": result.tokens_used,
        }
